# Generated by Django 5.1.7 on 2025-03-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plainte", "0002_report_delete_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="photo",
        ),
        migrations.AlterField(
            model_name="report",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
